### ISSUE TITLE
How can I get data from pentacam

### ISSUE THREAD

**Issue by sunshichen** [ouracademy/electrokeratoconus#2]
Hi, I'm very happy to find this repo about Keratinous. I'm currently doing some related tasks. Could you help us to access data from pentacam?  We are using OCULUS pentacam. Thanks greatly for your helps.

**Comment by artmadeit** [comment]
Hello,

Pentacam exports data in .udm files (a custom file format) and .csv files.
In the last case, these .csv files are located in where you install the pentacam (for example C://Pentacam/Autocsv/*.csv), you need to search this folder in your PC where the OCULUS pentacam is installed and you will see something like 
![image](https://user-images.githubusercontent.com/18428325/90802812-66e2a280-e2dd-11ea-959a-fa471515ca8d.png)


A current project to automatic read these files and watch every change in these .csv files can be seen in https://github.com/ouracademy/electrocornea. It currently sends a POST request to a harcoded URL.


best regards, cheers :beers:
